[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci --only=production"]

[phases.build]
dependsOn = ["install"]
cmds = ["echo 'No build step needed'"]

[start]
cmd = "node simple-server.js"
